export type Cards =
  | 'artist'
  | 'album'
  | 'playlist'
  | 'episode'
  | 'show'
  | 'topResult'
  | 'category'
  | 'artistDetail'
  | 'albumDetail'
  | 'showDetail'
  | 'episodeDetail'
  | 'episodeShowDetail'
  | 'playlistDetail'

export type TrackComponents = 'onPopular' | 'onAlbum' | 'onSearch' | 'onSongs';

export type Icons =
  | 'heart'
  | 'heart-green'
  | 'shuffle'
  | 'repeat'
  | 'skip-back'
  | 'skip-forward'
  | 'play-dark'
  | 'pause'
  | 'volume'
  | 'mute'
  | 'user'
  | 'chevron-filled'
  | 'chevron-left'
  | 'chevron-right'
  | 'search'
  | 'search-dark'
  | 'home'
  | 'library'
  | 'add'
  | 'heart-white'
  | 'play-white'
  | 'more-horizontal'
  | 'clock'
  | 'hashTag';
